# These are supported funding model platforms

github: [DevNova-ID]
patreon:
open_collective:
ko_fi:
tidelift: npm/@devnova-id/no-coding
community_bridge: no-coding
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
custom:
  - [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/F1F01DQNFC)
