# These are supported funding model platforms

github: [DevNova-ID]
patreon:
open_collective:
ko_fi: devnova_id
tidelift: npm/@devnova-id/no-coding
community_bridge: no-coding
liberapay:
polar:
buy_me_a_coffee:
thanks_dev:
custom:
